config/routes.rb
Rails.application.routes.draw do
  root 'chatrooms#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  mount ActionCable.server, at: '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { minimum: 1, maximum: 100 }
  validates :user_id, presence: true
  scope :custom_display, -> { order(:created_at).last(20)}

end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 15 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be loged in to perform that action"
      redirect_to login_path
    end
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mode_message: message_render(message)
    end 
  end
  
  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new
  end
  
  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:succes] = "Welcome to messanger #{@user.username}"
      redirect_to root_path
    else
      flash[:danger] = "Please try to register again"
      render "new"
    end  
  end

  private

  def user_params
    params.require(:user).permit(:username,:password)   
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular orange coffee icon"></i>
  Say something
</h4>
<div class="ui two column grid">
  <div class=" twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
         <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class=" four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
        <%= link_to "Chatroom", root_path, class: "item" %>
        <a class="item">
          Messages
        </a>
        <div class="right menu">
          <% if logged_in? %>
            <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
          <% else %>
            <%= link_to "Log in", login_path, class: "item" %>
            <%= link_to "Sign up", signup_path, class: "item" %>    
          <% end %>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MesaggeMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui inverted large menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>   
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>    
      <%= yield %>
      <hr>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up form</h1>
<div class="ui inverted segment">
  <div class="ui inverted form">
    <%= form_for(@user, class: "ui form", url: signup_path) do |f| %>
      <div class="field">
        <label>User Name</label>
        <%= f.text_field :username, placeholder: "Username" %>
      </div>
      <div class="field">
        <label>Password</label>
        <%= f.password_field :password, placeholder: "Password" %>
      </div>
      <div>
        <%= f.submit "Submit", class: "ui submit button" %>
      </div>
    <% end %>
  </div>
</div>